package pqt.gh.elaaj.model.vo;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.ValidationException;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewRowImpl;

import pqt.gh.elaaj.model.eo.ElaajClaimReimburstmentEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 20 12:49:12 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ElaajClaimReimburstmentEOVORowImpl extends ViewRowImpl {
    public static final int ENTITY_ELAAJCLAIMREIMBURSTMENTEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        AttachFile1,
        AttachFile2,
        AttachFile3,
        CellNo,
        CertificateNo,
        ClaimTotalAmount,
        CompanyName,
        DoctorPescription,
        ElaajClaimReimburstmentId,
        Email,
        EmployeeId,
        ExpectedCost,
        NameOfDoctor,
        NameOfEmployee,
        NameOfPanelHospital,
        NameOfPatient,
        ReimburstmentDate,
        SymptomAtPresent,
        TypeOfClaimn,
        AppMod,
        DmsDocumentReference,
        DocumentIdPk,
        Cnic,
        OtherHospital,
        ElaajClaimReimDmsDocEOVO,
        VuGhsElaajCoveredMemberVO1,
        PanelHospitalLovVO1,
        CoverDescriptionLovVO1,
        CoverDescNewLovVO1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int ATTACHFILE1 = AttributesEnum.AttachFile1.index();
    public static final int ATTACHFILE2 = AttributesEnum.AttachFile2.index();
    public static final int ATTACHFILE3 = AttributesEnum.AttachFile3.index();
    public static final int CELLNO = AttributesEnum.CellNo.index();
    public static final int CERTIFICATENO = AttributesEnum.CertificateNo.index();
    public static final int CLAIMTOTALAMOUNT = AttributesEnum.ClaimTotalAmount.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int DOCTORPESCRIPTION = AttributesEnum.DoctorPescription.index();
    public static final int ELAAJCLAIMREIMBURSTMENTID = AttributesEnum.ElaajClaimReimburstmentId.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int EXPECTEDCOST = AttributesEnum.ExpectedCost.index();
    public static final int NAMEOFDOCTOR = AttributesEnum.NameOfDoctor.index();
    public static final int NAMEOFEMPLOYEE = AttributesEnum.NameOfEmployee.index();
    public static final int NAMEOFPANELHOSPITAL = AttributesEnum.NameOfPanelHospital.index();
    public static final int NAMEOFPATIENT = AttributesEnum.NameOfPatient.index();
    public static final int REIMBURSTMENTDATE = AttributesEnum.ReimburstmentDate.index();
    public static final int SYMPTOMATPRESENT = AttributesEnum.SymptomAtPresent.index();
    public static final int TYPEOFCLAIMN = AttributesEnum.TypeOfClaimn.index();
    public static final int APPMOD = AttributesEnum.AppMod.index();
    public static final int DMSDOCUMENTREFERENCE = AttributesEnum.DmsDocumentReference.index();
    public static final int DOCUMENTIDPK = AttributesEnum.DocumentIdPk.index();
    public static final int CNIC = AttributesEnum.Cnic.index();
    public static final int OTHERHOSPITAL = AttributesEnum.OtherHospital.index();
    public static final int ELAAJCLAIMREIMDMSDOCEOVO = AttributesEnum.ElaajClaimReimDmsDocEOVO.index();
    public static final int VUGHSELAAJCOVEREDMEMBERVO1 = AttributesEnum.VuGhsElaajCoveredMemberVO1.index();
    public static final int PANELHOSPITALLOVVO1 = AttributesEnum.PanelHospitalLovVO1.index();
    public static final int COVERDESCRIPTIONLOVVO1 = AttributesEnum.CoverDescriptionLovVO1.index();
    public static final int COVERDESCNEWLOVVO1 = AttributesEnum.CoverDescNewLovVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ElaajClaimReimburstmentEOVORowImpl() {
    }

    /**
     * Gets ElaajClaimReimburstmentEO entity object.
     * @return the ElaajClaimReimburstmentEO
     */
    public ElaajClaimReimburstmentEOImpl getElaajClaimReimburstmentEO() {
        return (ElaajClaimReimburstmentEOImpl) getEntity(ENTITY_ELAAJCLAIMREIMBURSTMENTEO);
    }

    /**
     * Gets the attribute value for ATTACH_FILE_1 using the alias name AttachFile1.
     * @return the ATTACH_FILE_1
     */
    public String getAttachFile1() {
        return (String) getAttributeInternal(ATTACHFILE1);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH_FILE_1 using the alias name AttachFile1.
     * @param value value to set the ATTACH_FILE_1
     */
    public void setAttachFile1(String value) {
        setAttributeInternal(ATTACHFILE1, value);
    }

    /**
     * Gets the attribute value for ATTACH_FILE_2 using the alias name AttachFile2.
     * @return the ATTACH_FILE_2
     */
    public String getAttachFile2() {
        return (String) getAttributeInternal(ATTACHFILE2);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH_FILE_2 using the alias name AttachFile2.
     * @param value value to set the ATTACH_FILE_2
     */
    public void setAttachFile2(String value) {
        setAttributeInternal(ATTACHFILE2, value);
    }

    /**
     * Gets the attribute value for ATTACH_FILE_3 using the alias name AttachFile3.
     * @return the ATTACH_FILE_3
     */
    public String getAttachFile3() {
        return (String) getAttributeInternal(ATTACHFILE3);
    }

    /**
     * Sets <code>value</code> as attribute value for ATTACH_FILE_3 using the alias name AttachFile3.
     * @param value value to set the ATTACH_FILE_3
     */
    public void setAttachFile3(String value) {
        setAttributeInternal(ATTACHFILE3, value);
    }

    /**
     * Gets the attribute value for CELL_NO using the alias name CellNo.
     * @return the CELL_NO
     */
    public String getCellNo() {
        return (String) getAttributeInternal(CELLNO);
    }

    /**
     * Sets <code>value</code> as attribute value for CELL_NO using the alias name CellNo.
     * @param value value to set the CELL_NO
     */
    public void setCellNo(String value) {
        setAttributeInternal(CELLNO, value);
    }

    /**
     * Gets the attribute value for CERTIFICATE_NO using the alias name CertificateNo.
     * @return the CERTIFICATE_NO
     */
    public String getCertificateNo() {
        return (String) getAttributeInternal(CERTIFICATENO);
    }

    /**
     * Sets <code>value</code> as attribute value for CERTIFICATE_NO using the alias name CertificateNo.
     * @param value value to set the CERTIFICATE_NO
     */
    public void setCertificateNo(String value) {
        setAttributeInternal(CERTIFICATENO, value);
    }

    /**
     * Gets the attribute value for CLAIM_TOTAL_AMOUNT using the alias name ClaimTotalAmount.
     * @return the CLAIM_TOTAL_AMOUNT
     */
    public String getClaimTotalAmount() {
        return (String) getAttributeInternal(CLAIMTOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as attribute value for CLAIM_TOTAL_AMOUNT using the alias name ClaimTotalAmount.
     * @param value value to set the CLAIM_TOTAL_AMOUNT
     */
    public void setClaimTotalAmount(String value) {
        int vCheckAmount = 0;
        if (value != null){
            try{
                vCheckAmount = Integer.parseInt(value.toString());
            }catch(Exception e){
                vCheckAmount = 0;
            }
        }else if(value == null){
            throw new ValidationException("Please entered claim amount");
        }
        
        if(vCheckAmount == 0 || vCheckAmount < 0 ){
            throw new ValidationException("Please check entered amount");
        }else if(vCheckAmount > 25000){
            throw new ValidationException("Maximum limit of claim reimbursement via Elaaj is RS. 25,000/- For Claims greater than Rs.25,000/- please submit Hard copies through your HR Department.");            
        }
        
        setAttributeInternal(CLAIMTOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for COMPANY_NAME using the alias name CompanyName.
     * @return the COMPANY_NAME
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_NAME using the alias name CompanyName.
     * @param value value to set the COMPANY_NAME
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for DOCTOR_PESCRIPTION using the alias name DoctorPescription.
     * @return the DOCTOR_PESCRIPTION
     */
    public String getDoctorPescription() {
        return (String) getAttributeInternal(DOCTORPESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCTOR_PESCRIPTION using the alias name DoctorPescription.
     * @param value value to set the DOCTOR_PESCRIPTION
     */
    public void setDoctorPescription(String value) {
        setAttributeInternal(DOCTORPESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ELAAJ_CLAIM_REIMBURSTMENT_ID using the alias name ElaajClaimReimburstmentId.
     * @return the ELAAJ_CLAIM_REIMBURSTMENT_ID
     */
    public Number getElaajClaimReimburstmentId() {
        return (Number) getAttributeInternal(ELAAJCLAIMREIMBURSTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for ELAAJ_CLAIM_REIMBURSTMENT_ID using the alias name ElaajClaimReimburstmentId.
     * @param value value to set the ELAAJ_CLAIM_REIMBURSTMENT_ID
     */
    public void setElaajClaimReimburstmentId(Number value) {
        setAttributeInternal(ELAAJCLAIMREIMBURSTMENTID, value);
    }

    /**
     * Gets the attribute value for EMAIL using the alias name Email.
     * @return the EMAIL
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as attribute value for EMAIL using the alias name Email.
     * @param value value to set the EMAIL
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @return the EMPLOYEE_ID
     */
    public String getEmployeeId() {
        return (String) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setEmployeeId(String value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for EXPECTED_COST using the alias name ExpectedCost.
     * @return the EXPECTED_COST
     */
    public String getExpectedCost() {
        return (String) getAttributeInternal(EXPECTEDCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for EXPECTED_COST using the alias name ExpectedCost.
     * @param value value to set the EXPECTED_COST
     */
    public void setExpectedCost(String value) {
        setAttributeInternal(EXPECTEDCOST, value);
    }

    /**
     * Gets the attribute value for NAME_OF_DOCTOR using the alias name NameOfDoctor.
     * @return the NAME_OF_DOCTOR
     */
    public String getNameOfDoctor() {
        return (String) getAttributeInternal(NAMEOFDOCTOR);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_OF_DOCTOR using the alias name NameOfDoctor.
     * @param value value to set the NAME_OF_DOCTOR
     */
    public void setNameOfDoctor(String value) {
        setAttributeInternal(NAMEOFDOCTOR, value);
    }

    /**
     * Gets the attribute value for NAME_OF_EMPLOYEE using the alias name NameOfEmployee.
     * @return the NAME_OF_EMPLOYEE
     */
    public String getNameOfEmployee() {
        return (String) getAttributeInternal(NAMEOFEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_OF_EMPLOYEE using the alias name NameOfEmployee.
     * @param value value to set the NAME_OF_EMPLOYEE
     */
    public void setNameOfEmployee(String value) {
        setAttributeInternal(NAMEOFEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for NAME_OF_PANEL_HOSPITAL using the alias name NameOfPanelHospital.
     * @return the NAME_OF_PANEL_HOSPITAL
     */
    public String getNameOfPanelHospital() {
        return (String) getAttributeInternal(NAMEOFPANELHOSPITAL);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_OF_PANEL_HOSPITAL using the alias name NameOfPanelHospital.
     * @param value value to set the NAME_OF_PANEL_HOSPITAL
     */
    public void setNameOfPanelHospital(String value) {
        setAttributeInternal(NAMEOFPANELHOSPITAL, value);
    }

    /**
     * Gets the attribute value for NAME_OF_PATIENT using the alias name NameOfPatient.
     * @return the NAME_OF_PATIENT
     */
    public String getNameOfPatient() {
        return (String) getAttributeInternal(NAMEOFPATIENT);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_OF_PATIENT using the alias name NameOfPatient.
     * @param value value to set the NAME_OF_PATIENT
     */
    public void setNameOfPatient(String value) {
        setAttributeInternal(NAMEOFPATIENT, value);
    }

    /**
     * Gets the attribute value for REIMBURSTMENT_DATE using the alias name ReimburstmentDate.
     * @return the REIMBURSTMENT_DATE
     */
    public Date getReimburstmentDate() {
        return (Date) getAttributeInternal(REIMBURSTMENTDATE);
    }

    /**
     * Gets the attribute value for SYMPTOM_AT_PRESENT using the alias name SymptomAtPresent.
     * @return the SYMPTOM_AT_PRESENT
     */
    public String getSymptomAtPresent() {
        return (String) getAttributeInternal(SYMPTOMATPRESENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SYMPTOM_AT_PRESENT using the alias name SymptomAtPresent.
     * @param value value to set the SYMPTOM_AT_PRESENT
     */
    public void setSymptomAtPresent(String value) {
        setAttributeInternal(SYMPTOMATPRESENT, value);
    }

    /**
     * Gets the attribute value for TYPE_OF_CLAIMN using the alias name TypeOfClaimn.
     * @return the TYPE_OF_CLAIMN
     */
    public String getTypeOfClaimn() {
        return (String) getAttributeInternal(TYPEOFCLAIMN);
    }

    /**
     * Sets <code>value</code> as attribute value for TYPE_OF_CLAIMN using the alias name TypeOfClaimn.
     * @param value value to set the TYPE_OF_CLAIMN
     */
    public void setTypeOfClaimn(String value) {
        setAttributeInternal(TYPEOFCLAIMN, value);
    }

    /**
     * Gets the attribute value for APP_MOD using the alias name AppMod.
     * @return the APP_MOD
     */
    public String getAppMod() {
        return (String) getAttributeInternal(APPMOD);
    }

    /**
     * Sets <code>value</code> as attribute value for APP_MOD using the alias name AppMod.
     * @param value value to set the APP_MOD
     */
    public void setAppMod(String value) {
        setAttributeInternal(APPMOD, value);
    }

    /**
     * Gets the attribute value for DMS_DOCUMENT_REFERENCE using the alias name DmsDocumentReference.
     * @return the DMS_DOCUMENT_REFERENCE
     */
    public String getDmsDocumentReference() {
        return (String) getAttributeInternal(DMSDOCUMENTREFERENCE);
    }

    /**
     * Sets <code>value</code> as attribute value for DMS_DOCUMENT_REFERENCE using the alias name DmsDocumentReference.
     * @param value value to set the DMS_DOCUMENT_REFERENCE
     */
    public void setDmsDocumentReference(String value) {
        setAttributeInternal(DMSDOCUMENTREFERENCE, value);
    }

    /**
     * Gets the attribute value for DOCUMENT_ID_PK using the alias name DocumentIdPk.
     * @return the DOCUMENT_ID_PK
     */
    public Number getDocumentIdPk() {
        return (Number) getAttributeInternal(DOCUMENTIDPK);
    }

    /**
     * Sets <code>value</code> as attribute value for DOCUMENT_ID_PK using the alias name DocumentIdPk.
     * @param value value to set the DOCUMENT_ID_PK
     */
    public void setDocumentIdPk(Number value) {
        setAttributeInternal(DOCUMENTIDPK, value);
    }

    /**
     * Gets the attribute value for CNIC using the alias name Cnic.
     * @return the CNIC
     */
    public String getCnic() {
        return (String) getAttributeInternal(CNIC);
    }

    /**
     * Sets <code>value</code> as attribute value for CNIC using the alias name Cnic.
     * @param value value to set the CNIC
     */
    public void setCnic(String value) {
        setAttributeInternal(CNIC, value);
    }

    /**
     * Gets the attribute value for OTHER_HOSPITAL using the alias name OtherHospital.
     * @return the OTHER_HOSPITAL
     */
    public String getOtherHospital() {
        return (String) getAttributeInternal(OTHERHOSPITAL);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_HOSPITAL using the alias name OtherHospital.
     * @param value value to set the OTHER_HOSPITAL
     */
    public void setOtherHospital(String value) {
        setAttributeInternal(OTHERHOSPITAL, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ElaajClaimReimDmsDocEOVO.
     */
    public RowIterator getElaajClaimReimDmsDocEOVO() {
        return (RowIterator) getAttributeInternal(ELAAJCLAIMREIMDMSDOCEOVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> VuGhsElaajCoveredMemberVO1.
     */
    public RowSet getVuGhsElaajCoveredMemberVO1() {
        return (RowSet) getAttributeInternal(VUGHSELAAJCOVEREDMEMBERVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> PanelHospitalLovVO1.
     */
    public RowSet getPanelHospitalLovVO1() {
        return (RowSet) getAttributeInternal(PANELHOSPITALLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CoverDescriptionLovVO1.
     */
    public RowSet getCoverDescriptionLovVO1() {
        return (RowSet) getAttributeInternal(COVERDESCRIPTIONLOVVO1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> CoverDescNewLovVO1.
     */
    public RowSet getCoverDescNewLovVO1() {
        return (RowSet) getAttributeInternal(COVERDESCNEWLOVVO1);
    }
}

