package pqt.gh.elaaj.model.eo;

import java.math.BigDecimal;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 09 10:09:26 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ElaajClaimReimburstmentEOImpl extends EntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ElaajClaimReimburstmentId,
        CompanyName,
        NameOfEmployee,
        NameOfPatient,
        CertificateNo,
        EmployeeId,
        CellNo,
        Email,
        TypeOfClaimn,
        NameOfPanelHospital,
        NameOfDoctor,
        SymptomAtPresent,
        ClaimTotalAmount,
        ExpectedCost,
        DoctorPescription,
        AttachFile1,
        AttachFile2,
        AttachFile3,
        ReimburstmentDate,
        AppMod,
        DmsDocumentReference,
        DocumentIdPk,
        Cnic,
        OtherHospital,
        ElaajClaimReimDmsDocEO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ELAAJCLAIMREIMBURSTMENTID = AttributesEnum.ElaajClaimReimburstmentId.index();
    public static final int COMPANYNAME = AttributesEnum.CompanyName.index();
    public static final int NAMEOFEMPLOYEE = AttributesEnum.NameOfEmployee.index();
    public static final int NAMEOFPATIENT = AttributesEnum.NameOfPatient.index();
    public static final int CERTIFICATENO = AttributesEnum.CertificateNo.index();
    public static final int EMPLOYEEID = AttributesEnum.EmployeeId.index();
    public static final int CELLNO = AttributesEnum.CellNo.index();
    public static final int EMAIL = AttributesEnum.Email.index();
    public static final int TYPEOFCLAIMN = AttributesEnum.TypeOfClaimn.index();
    public static final int NAMEOFPANELHOSPITAL = AttributesEnum.NameOfPanelHospital.index();
    public static final int NAMEOFDOCTOR = AttributesEnum.NameOfDoctor.index();
    public static final int SYMPTOMATPRESENT = AttributesEnum.SymptomAtPresent.index();
    public static final int CLAIMTOTALAMOUNT = AttributesEnum.ClaimTotalAmount.index();
    public static final int EXPECTEDCOST = AttributesEnum.ExpectedCost.index();
    public static final int DOCTORPESCRIPTION = AttributesEnum.DoctorPescription.index();
    public static final int ATTACHFILE1 = AttributesEnum.AttachFile1.index();
    public static final int ATTACHFILE2 = AttributesEnum.AttachFile2.index();
    public static final int ATTACHFILE3 = AttributesEnum.AttachFile3.index();
    public static final int REIMBURSTMENTDATE = AttributesEnum.ReimburstmentDate.index();
    public static final int APPMOD = AttributesEnum.AppMod.index();
    public static final int DMSDOCUMENTREFERENCE = AttributesEnum.DmsDocumentReference.index();
    public static final int DOCUMENTIDPK = AttributesEnum.DocumentIdPk.index();
    public static final int CNIC = AttributesEnum.Cnic.index();
    public static final int OTHERHOSPITAL = AttributesEnum.OtherHospital.index();
    public static final int ELAAJCLAIMREIMDMSDOCEO = AttributesEnum.ElaajClaimReimDmsDocEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ElaajClaimReimburstmentEOImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("pqt.gh.elaaj.model.eo.ElaajClaimReimburstmentEO");
    }


    /**
     * Gets the attribute value for ElaajClaimReimburstmentId, using the alias name ElaajClaimReimburstmentId.
     * @return the value of ElaajClaimReimburstmentId
     */
    public Number getElaajClaimReimburstmentId() {
        return (Number) getAttributeInternal(ELAAJCLAIMREIMBURSTMENTID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ElaajClaimReimburstmentId.
     * @param value value to set the ElaajClaimReimburstmentId
     */
    public void setElaajClaimReimburstmentId(Number value) {
        setAttributeInternal(ELAAJCLAIMREIMBURSTMENTID, value);
    }

    /**
     * Gets the attribute value for CompanyName, using the alias name CompanyName.
     * @return the value of CompanyName
     */
    public String getCompanyName() {
        return (String) getAttributeInternal(COMPANYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyName.
     * @param value value to set the CompanyName
     */
    public void setCompanyName(String value) {
        setAttributeInternal(COMPANYNAME, value);
    }

    /**
     * Gets the attribute value for NameOfEmployee, using the alias name NameOfEmployee.
     * @return the value of NameOfEmployee
     */
    public String getNameOfEmployee() {
        return (String) getAttributeInternal(NAMEOFEMPLOYEE);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameOfEmployee.
     * @param value value to set the NameOfEmployee
     */
    public void setNameOfEmployee(String value) {
        setAttributeInternal(NAMEOFEMPLOYEE, value);
    }

    /**
     * Gets the attribute value for NameOfPatient, using the alias name NameOfPatient.
     * @return the value of NameOfPatient
     */
    public String getNameOfPatient() {
        return (String) getAttributeInternal(NAMEOFPATIENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameOfPatient.
     * @param value value to set the NameOfPatient
     */
    public void setNameOfPatient(String value) {
        setAttributeInternal(NAMEOFPATIENT, value);
    }

    /**
     * Gets the attribute value for CertificateNo, using the alias name CertificateNo.
     * @return the value of CertificateNo
     */
    public String getCertificateNo() {
        return (String) getAttributeInternal(CERTIFICATENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CertificateNo.
     * @param value value to set the CertificateNo
     */
    public void setCertificateNo(String value) {
        setAttributeInternal(CERTIFICATENO, value);
    }

    /**
     * Gets the attribute value for EmployeeId, using the alias name EmployeeId.
     * @return the value of EmployeeId
     */
    public String getEmployeeId() {
        return (String) getAttributeInternal(EMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for EmployeeId.
     * @param value value to set the EmployeeId
     */
    public void setEmployeeId(String value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for CellNo, using the alias name CellNo.
     * @return the value of CellNo
     */
    public String getCellNo() {
        return (String) getAttributeInternal(CELLNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CellNo.
     * @param value value to set the CellNo
     */
    public void setCellNo(String value) {
        setAttributeInternal(CELLNO, value);
    }

    /**
     * Gets the attribute value for Email, using the alias name Email.
     * @return the value of Email
     */
    public String getEmail() {
        return (String) getAttributeInternal(EMAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Email.
     * @param value value to set the Email
     */
    public void setEmail(String value) {
        setAttributeInternal(EMAIL, value);
    }

    /**
     * Gets the attribute value for TypeOfClaimn, using the alias name TypeOfClaimn.
     * @return the value of TypeOfClaimn
     */
    public String getTypeOfClaimn() {
        return (String) getAttributeInternal(TYPEOFCLAIMN);
    }

    /**
     * Sets <code>value</code> as the attribute value for TypeOfClaimn.
     * @param value value to set the TypeOfClaimn
     */
    public void setTypeOfClaimn(String value) {
        setAttributeInternal(TYPEOFCLAIMN, value);
    }

    /**
     * Gets the attribute value for NameOfPanelHospital, using the alias name NameOfPanelHospital.
     * @return the value of NameOfPanelHospital
     */
    public String getNameOfPanelHospital() {
        return (String) getAttributeInternal(NAMEOFPANELHOSPITAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameOfPanelHospital.
     * @param value value to set the NameOfPanelHospital
     */
    public void setNameOfPanelHospital(String value) {
        setAttributeInternal(NAMEOFPANELHOSPITAL, value);
    }

    /**
     * Gets the attribute value for NameOfDoctor, using the alias name NameOfDoctor.
     * @return the value of NameOfDoctor
     */
    public String getNameOfDoctor() {
        return (String) getAttributeInternal(NAMEOFDOCTOR);
    }

    /**
     * Sets <code>value</code> as the attribute value for NameOfDoctor.
     * @param value value to set the NameOfDoctor
     */
    public void setNameOfDoctor(String value) {
        setAttributeInternal(NAMEOFDOCTOR, value);
    }

    /**
     * Gets the attribute value for SymptomAtPresent, using the alias name SymptomAtPresent.
     * @return the value of SymptomAtPresent
     */
    public String getSymptomAtPresent() {
        return (String) getAttributeInternal(SYMPTOMATPRESENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for SymptomAtPresent.
     * @param value value to set the SymptomAtPresent
     */
    public void setSymptomAtPresent(String value) {
        setAttributeInternal(SYMPTOMATPRESENT, value);
    }

    /**
     * Gets the attribute value for ClaimTotalAmount, using the alias name ClaimTotalAmount.
     * @return the value of ClaimTotalAmount
     */
    public String getClaimTotalAmount() {
        return (String) getAttributeInternal(CLAIMTOTALAMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ClaimTotalAmount.
     * @param value value to set the ClaimTotalAmount
     */
    public void setClaimTotalAmount(String value) {
        setAttributeInternal(CLAIMTOTALAMOUNT, value);
    }

    /**
     * Gets the attribute value for ExpectedCost, using the alias name ExpectedCost.
     * @return the value of ExpectedCost
     */
    public String getExpectedCost() {
        return (String) getAttributeInternal(EXPECTEDCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for ExpectedCost.
     * @param value value to set the ExpectedCost
     */
    public void setExpectedCost(String value) {
        setAttributeInternal(EXPECTEDCOST, value);
    }

    /**
     * Gets the attribute value for DoctorPescription, using the alias name DoctorPescription.
     * @return the value of DoctorPescription
     */
    public String getDoctorPescription() {
        return (String) getAttributeInternal(DOCTORPESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for DoctorPescription.
     * @param value value to set the DoctorPescription
     */
    public void setDoctorPescription(String value) {
        setAttributeInternal(DOCTORPESCRIPTION, value);
    }

    /**
     * Gets the attribute value for AttachFile1, using the alias name AttachFile1.
     * @return the value of AttachFile1
     */
    public String getAttachFile1() {
        return (String) getAttributeInternal(ATTACHFILE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttachFile1.
     * @param value value to set the AttachFile1
     */
    public void setAttachFile1(String value) {
        setAttributeInternal(ATTACHFILE1, value);
    }

    /**
     * Gets the attribute value for AttachFile2, using the alias name AttachFile2.
     * @return the value of AttachFile2
     */
    public String getAttachFile2() {
        return (String) getAttributeInternal(ATTACHFILE2);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttachFile2.
     * @param value value to set the AttachFile2
     */
    public void setAttachFile2(String value) {
        setAttributeInternal(ATTACHFILE2, value);
    }

    /**
     * Gets the attribute value for AttachFile3, using the alias name AttachFile3.
     * @return the value of AttachFile3
     */
    public String getAttachFile3() {
        return (String) getAttributeInternal(ATTACHFILE3);
    }

    /**
     * Sets <code>value</code> as the attribute value for AttachFile3.
     * @param value value to set the AttachFile3
     */
    public void setAttachFile3(String value) {
        setAttributeInternal(ATTACHFILE3, value);
    }

    /**
     * Gets the attribute value for ReimburstmentDate, using the alias name ReimburstmentDate.
     * @return the value of ReimburstmentDate
     */
    public Date getReimburstmentDate() {
        return (Date) getAttributeInternal(REIMBURSTMENTDATE);
    }

    /**
     * Gets the attribute value for AppMod, using the alias name AppMod.
     * @return the value of AppMod
     */
    public String getAppMod() {
        return (String) getAttributeInternal(APPMOD);
    }

    /**
     * Sets <code>value</code> as the attribute value for AppMod.
     * @param value value to set the AppMod
     */
    public void setAppMod(String value) {
        setAttributeInternal(APPMOD, value);
    }


    /**
     * Gets the attribute value for DmsDocumentReference, using the alias name DmsDocumentReference.
     * @return the value of DmsDocumentReference
     */
    public String getDmsDocumentReference() {
        return (String) getAttributeInternal(DMSDOCUMENTREFERENCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for DmsDocumentReference.
     * @param value value to set the DmsDocumentReference
     */
    public void setDmsDocumentReference(String value) {
        setAttributeInternal(DMSDOCUMENTREFERENCE, value);
    }

    /**
     * Gets the attribute value for DocumentIdPk, using the alias name DocumentIdPk.
     * @return the value of DocumentIdPk
     */
    public Number getDocumentIdPk() {
        return (Number) getAttributeInternal(DOCUMENTIDPK);
    }

    /**
     * Sets <code>value</code> as the attribute value for DocumentIdPk.
     * @param value value to set the DocumentIdPk
     */
    public void setDocumentIdPk(Number value) {
        setAttributeInternal(DOCUMENTIDPK, value);
    }

    /**
     * Gets the attribute value for Cnic, using the alias name Cnic.
     * @return the value of Cnic
     */
    public String getCnic() {
        return (String) getAttributeInternal(CNIC);
    }

    /**
     * Sets <code>value</code> as the attribute value for Cnic.
     * @param value value to set the Cnic
     */
    public void setCnic(String value) {
        setAttributeInternal(CNIC, value);
    }

    /**
     * Gets the attribute value for OtherHospital, using the alias name OtherHospital.
     * @return the value of OtherHospital
     */
    public String getOtherHospital() {
        return (String) getAttributeInternal(OTHERHOSPITAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for OtherHospital.
     * @param value value to set the OtherHospital
     */
    public void setOtherHospital(String value) {
        setAttributeInternal(OTHERHOSPITAL, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getElaajClaimReimDmsDocEO() {
        return (RowIterator) getAttributeInternal(ELAAJCLAIMREIMDMSDOCEO);
    }


    /**
     * @param elaajClaimReimburstmentId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number elaajClaimReimburstmentId) {
        return new Key(new Object[] { elaajClaimReimburstmentId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        oracle.jbo.server.SequenceImpl seq =
                    new oracle.jbo.server.SequenceImpl("elaaj_claim_reimburstment_squ", getDBTransaction());
                setElaajClaimReimburstmentId(seq.getSequenceNumber());
                setAppMod("ADF");
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

